In [2]:
import pandas as pd
import sklearn # pip install sklearn
from sklearn import ensemble
import numpy as np

## Iris

In [6]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])

In [8]:
df.T

0            1            2            3            4    \
sepal_length          5.1          4.9          4.7          4.6            5   
sepal_width           3.5            3          3.2          3.1          3.6   
petal_length          1.4          1.4          1.3          1.5          1.4   
petal_width           0.2          0.2          0.2          0.2          0.2   
class         Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa   

                      5            6            7            8            9    \
sepal_length          5.4          4.6            5          4.4          4.9   
sepal_width           3.9          3.4          3.4          2.9          3.1   
petal_length          1.7          1.4          1.5          1.4          1.5   
petal_width           0.4          0.3          0.2          0.2          0.1   
class         Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa   

                   ...                   140             141             142  \
sepal_length       ...                   6.7             6.9             5.8   
sepal_width        ...                   3.1             3.1             2.7   
petal_length       ...                   5.6             5.1             5.1   
petal_width        ...                   2.4             2.3             1.9   
class              ...        Iris-virginica  Iris-virginica  Iris-virginica   

                         143             144             145             146  \
sepal_length             6.8             6.7             6.7             6.3   
sepal_width              3.2             3.3               3             2.5   
petal_length             5.9             5.7             5.2               5   
petal_width              2.3             2.5             2.3             1.9   
class         Iris-virginica  Iris-virginica  Iris-virginica  Iris-virginica   

                         147             148             149  
sepal_length             6.5             6.2             5.9  
sepal_width                3             3.4               3  
petal_length             5.2             5.4             5.1  
petal_width                2             2.3             1.8  
class         Iris-virginica  Iris-virginica  Iris-virginica  

[5 rows x 150 columns]

## Feature Vectors

In [34]:
cols

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [36]:
reg = ensemble.RandomForestRegressor()
X = df[cols[1:]]
y = df[cols[0]]
reg.fit(X, y)

ValueError: could not convert string to float: 'Iris-virginica'

In [37]:
pd.get_dummies(df['class'])

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
5              1                0               0
6              1                0               0
7              1                0               0
8              1                0               0
9              1                0               0
10             1                0               0
11             1                0               0
12             1                0               0
13             1                0               0
14             1                0               0
15             1                0               0
16             1                0               0
17             1                0               0
18             1                0               0
19             1                0               0
20             1                0               0
21             1                0               0
22             1                0               0
23             1                0               0
24             1                0               0
25             1                0               0
26             1                0               0
27             1                0               0
28             1                0               0
29             1                0               0
..           ...              ...             ...
120            0                0               1
121            0                0               1
122            0                0               1
123            0                0               1
124            0                0               1
125            0                0               1
126            0                0               1
127            0                0               1
128            0                0               1
129            0                0               1
130            0                0               1
131            0                0               1
132            0                0               1
133            0                0               1
134            0                0               1
135            0                0               1
136            0                0               1
137            0                0               1
138            0                0               1
139            0                0               1
140            0                0               1
141            0                0               1
142            0                0               1
143            0                0               1
144            0                0               1
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [38]:
X = pd.concat([df[cols[1:-1]], pd.get_dummies(df['class'])], axis=1)

In [40]:
reg.fit(X, y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [41]:
reg.predict([[2, 1, .1, 1, 0, 0]])

array([ 4.48])

In [41]:
reg.predict([[2, 1, .1, 1, 0, 0]])

array([ 4.48])

In [42]:
df.groupby('class').describe()[cols[:-1]]

sepal_length  sepal_width  petal_length  petal_width
class                                                                      
Iris-setosa     count     50.000000    50.000000     50.000000    50.000000
                mean       5.006000     3.418000      1.464000     0.244000
                std        0.352490     0.381024      0.173511     0.107210
                min        4.300000     2.300000      1.000000     0.100000
                25%        4.800000     3.125000      1.400000     0.200000
                50%        5.000000     3.400000      1.500000     0.200000
                75%        5.200000     3.675000      1.575000     0.300000
                max        5.800000     4.400000      1.900000     0.600000
Iris-versicolor count     50.000000    50.000000     50.000000    50.000000
                mean       5.936000     2.770000      4.260000     1.326000
                std        0.516171     0.313798      0.469911     0.197753
                min        4.900000     2.000000      3.000000     1.000000
                25%        5.600000     2.525000      4.000000     1.200000
                50%        5.900000     2.800000      4.350000     1.300000
                75%        6.300000     3.000000      4.600000     1.500000
                max        7.000000     3.400000      5.100000     1.800000
Iris-virginica  count     50.000000    50.000000     50.000000    50.000000
                mean       6.588000     2.974000      5.552000     2.026000
                std        0.635880     0.322497      0.551895     0.274650
                min        4.900000     2.200000      4.500000     1.400000
                25%        6.225000     2.800000      5.100000     1.800000
                50%        6.500000     3.000000      5.550000     2.000000
                75%        6.900000     3.175000      5.875000     2.300000
                max        7.900000     3.800000      6.900000     2.500000

In [43]:
reg.predict([[3.2, 5.8, 2.3, 0, 0, 1]])

array([ 6.75])